<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            // EU Countries cu VIES
            ['code' => 'AT', 'name' => 'Austria', 'vat_rate' => 20.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'BE', 'name' => 'Belgium', 'vat_rate' => 21.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'vat_rate' => 20.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'BGN', 'continent' => 'Europe'],
            ['code' => 'HR', 'name' => 'Croatia', 'vat_rate' => 25.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'CY', 'name' => 'Cyprus', 'vat_rate' => 19.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'vat_rate' => 21.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'CZK', 'continent' => 'Europe'],
            ['code' => 'DK', 'name' => 'Denmark', 'vat_rate' => 25.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'DKK', 'continent' => 'Europe'],
            ['code' => 'EE', 'name' => 'Estonia', 'vat_rate' => 20.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'FI', 'name' => 'Finland', 'vat_rate' => 24.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'FR', 'name' => 'France', 'vat_rate' => 20.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'DE', 'name' => 'Germany', 'vat_rate' => 19.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'GR', 'name' => 'Greece', 'vat_rate' => 24.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'HU', 'name' => 'Hungary', 'vat_rate' => 27.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'HUF', 'continent' => 'Europe'],
            ['code' => 'IE', 'name' => 'Ireland', 'vat_rate' => 23.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'IT', 'name' => 'Italy', 'vat_rate' => 22.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'LV', 'name' => 'Latvia', 'vat_rate' => 21.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'LT', 'name' => 'Lithuania', 'vat_rate' => 21.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'LU', 'name' => 'Luxembourg', 'vat_rate' => 17.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'MT', 'name' => 'Malta', 'vat_rate' => 18.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'NL', 'name' => 'Netherlands', 'vat_rate' => 21.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'PL', 'name' => 'Poland', 'vat_rate' => 23.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'PLN', 'continent' => 'Europe'],
            ['code' => 'PT', 'name' => 'Portugal', 'vat_rate' => 23.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'RO', 'name' => 'Romania', 'vat_rate' => 19.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'RON', 'continent' => 'Europe'],
            ['code' => 'SK', 'name' => 'Slovakia', 'vat_rate' => 20.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'SI', 'name' => 'Slovenia', 'vat_rate' => 22.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'ES', 'name' => 'Spain', 'vat_rate' => 21.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'SE', 'name' => 'Sweden', 'vat_rate' => 25.00, 'is_eu_member' => true, 'vies_validation_required' => true, 'currency_code' => 'SEK', 'continent' => 'Europe'],

            // Non-EU Europe
            ['code' => 'GB', 'name' => 'United Kingdom', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'GBP', 'continent' => 'Europe'],
            ['code' => 'CH', 'name' => 'Switzerland', 'vat_rate' => 7.70, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CHF', 'continent' => 'Europe'],
            ['code' => 'NO', 'name' => 'Norway', 'vat_rate' => 25.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'NOK', 'continent' => 'Europe'],
            ['code' => 'IS', 'name' => 'Iceland', 'vat_rate' => 24.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ISK', 'continent' => 'Europe'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'vat_rate' => 7.70, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CHF', 'continent' => 'Europe'],
            ['code' => 'MC', 'name' => 'Monaco', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'AD', 'name' => 'Andorra', 'vat_rate' => 4.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'SM', 'name' => 'San Marino', 'vat_rate' => 17.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'VA', 'name' => 'Vatican City', 'vat_rate' => 22.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'AL', 'name' => 'Albania', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ALL', 'continent' => 'Europe'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'vat_rate' => 17.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BAM', 'continent' => 'Europe'],
            ['code' => 'XK', 'name' => 'Kosovo', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'ME', 'name' => 'Montenegro', 'vat_rate' => 21.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'EUR', 'continent' => 'Europe'],
            ['code' => 'MK', 'name' => 'North Macedonia', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MKD', 'continent' => 'Europe'],
            ['code' => 'RS', 'name' => 'Serbia', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'RSD', 'continent' => 'Europe'],
            ['code' => 'MD', 'name' => 'Moldova', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MDL', 'continent' => 'Europe'],
            ['code' => 'UA', 'name' => 'Ukraine', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'UAH', 'continent' => 'Europe'],
            ['code' => 'BY', 'name' => 'Belarus', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BYN', 'continent' => 'Europe'],
            ['code' => 'RU', 'name' => 'Russia', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'RUB', 'continent' => 'Europe'],

            // North America
            ['code' => 'US', 'name' => 'United States', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'USD', 'continent' => 'North America'],
            ['code' => 'CA', 'name' => 'Canada', 'vat_rate' => 5.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CAD', 'continent' => 'North America'],
            ['code' => 'MX', 'name' => 'Mexico', 'vat_rate' => 16.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MXN', 'continent' => 'North America'],
            ['code' => 'GT', 'name' => 'Guatemala', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'GTQ', 'continent' => 'North America'],
            ['code' => 'BZ', 'name' => 'Belize', 'vat_rate' => 12.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BZD', 'continent' => 'North America'],
            ['code' => 'SV', 'name' => 'El Salvador', 'vat_rate' => 13.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'USD', 'continent' => 'North America'],
            ['code' => 'HN', 'name' => 'Honduras', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'HNL', 'continent' => 'North America'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'NIO', 'continent' => 'North America'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'vat_rate' => 13.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CRC', 'continent' => 'North America'],
            ['code' => 'PA', 'name' => 'Panama', 'vat_rate' => 7.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'PAB', 'continent' => 'North America'],

            // South America
            ['code' => 'BR', 'name' => 'Brazil', 'vat_rate' => 17.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BRL', 'continent' => 'South America'],
            ['code' => 'AR', 'name' => 'Argentina', 'vat_rate' => 21.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ARS', 'continent' => 'South America'],
            ['code' => 'CL', 'name' => 'Chile', 'vat_rate' => 19.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CLP', 'continent' => 'South America'],
            ['code' => 'CO', 'name' => 'Colombia', 'vat_rate' => 19.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'COP', 'continent' => 'South America'],
            ['code' => 'PE', 'name' => 'Peru', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'PEN', 'continent' => 'South America'],
            ['code' => 'VE', 'name' => 'Venezuela', 'vat_rate' => 16.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'VES', 'continent' => 'South America'],
            ['code' => 'EC', 'name' => 'Ecuador', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'USD', 'continent' => 'South America'],
            ['code' => 'BO', 'name' => 'Bolivia', 'vat_rate' => 13.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BOB', 'continent' => 'South America'],
            ['code' => 'PY', 'name' => 'Paraguay', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'PYG', 'continent' => 'South America'],
            ['code' => 'UY', 'name' => 'Uruguay', 'vat_rate' => 22.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'UYU', 'continent' => 'South America'],
            ['code' => 'GY', 'name' => 'Guyana', 'vat_rate' => 14.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'GYD', 'continent' => 'South America'],
            ['code' => 'SR', 'name' => 'Suriname', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SRD', 'continent' => 'South America'],

            // Asia
            ['code' => 'CN', 'name' => 'China', 'vat_rate' => 13.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CNY', 'continent' => 'Asia'],
            ['code' => 'IN', 'name' => 'India', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'INR', 'continent' => 'Asia'],
            ['code' => 'JP', 'name' => 'Japan', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'JPY', 'continent' => 'Asia'],
            ['code' => 'KR', 'name' => 'South Korea', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'KRW', 'continent' => 'Asia'],
            ['code' => 'TH', 'name' => 'Thailand', 'vat_rate' => 7.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'THB', 'continent' => 'Asia'],
            ['code' => 'VN', 'name' => 'Vietnam', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'VND', 'continent' => 'Asia'],
            ['code' => 'SG', 'name' => 'Singapore', 'vat_rate' => 7.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SGD', 'continent' => 'Asia'],
            ['code' => 'MY', 'name' => 'Malaysia', 'vat_rate' => 6.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MYR', 'continent' => 'Asia'],
            ['code' => 'ID', 'name' => 'Indonesia', 'vat_rate' => 11.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'IDR', 'continent' => 'Asia'],
            ['code' => 'PH', 'name' => 'Philippines', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'PHP', 'continent' => 'Asia'],
            ['code' => 'TW', 'name' => 'Taiwan', 'vat_rate' => 5.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'TWD', 'continent' => 'Asia'],
            ['code' => 'HK', 'name' => 'Hong Kong', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'HKD', 'continent' => 'Asia'],
            ['code' => 'MO', 'name' => 'Macau', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MOP', 'continent' => 'Asia'],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'vat_rate' => 5.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AED', 'continent' => 'Asia'],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SAR', 'continent' => 'Asia'],
            ['code' => 'IL', 'name' => 'Israel', 'vat_rate' => 17.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ILS', 'continent' => 'Asia'],
            ['code' => 'TR', 'name' => 'Turkey', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'TRY', 'continent' => 'Asia'],
            ['code' => 'IR', 'name' => 'Iran', 'vat_rate' => 9.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'IRR', 'continent' => 'Asia'],
            ['code' => 'IQ', 'name' => 'Iraq', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'IQD', 'continent' => 'Asia'],
            ['code' => 'PK', 'name' => 'Pakistan', 'vat_rate' => 17.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'PKR', 'continent' => 'Asia'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BDT', 'continent' => 'Asia'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'LKR', 'continent' => 'Asia'],
            ['code' => 'MM', 'name' => 'Myanmar', 'vat_rate' => 5.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MMK', 'continent' => 'Asia'],
            ['code' => 'KH', 'name' => 'Cambodia', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'KHR', 'continent' => 'Asia'],
            ['code' => 'LA', 'name' => 'Laos', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'LAK', 'continent' => 'Asia'],
            ['code' => 'NP', 'name' => 'Nepal', 'vat_rate' => 13.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'NPR', 'continent' => 'Asia'],
            ['code' => 'BT', 'name' => 'Bhutan', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BTN', 'continent' => 'Asia'],
            ['code' => 'MN', 'name' => 'Mongolia', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MNT', 'continent' => 'Asia'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'KZT', 'continent' => 'Asia'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'UZS', 'continent' => 'Asia'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'KGS', 'continent' => 'Asia'],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'TJS', 'continent' => 'Asia'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'TMT', 'continent' => 'Asia'],
            ['code' => 'AF', 'name' => 'Afghanistan', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AFN', 'continent' => 'Asia'],
            ['code' => 'AM', 'name' => 'Armenia', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AMD', 'continent' => 'Asia'],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AZN', 'continent' => 'Asia'],
            ['code' => 'GE', 'name' => 'Georgia', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'GEL', 'continent' => 'Asia'],
            ['code' => 'JO', 'name' => 'Jordan', 'vat_rate' => 16.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'JOD', 'continent' => 'Asia'],
            ['code' => 'LB', 'name' => 'Lebanon', 'vat_rate' => 11.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'LBP', 'continent' => 'Asia'],
            ['code' => 'SY', 'name' => 'Syria', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SYP', 'continent' => 'Asia'],
            ['code' => 'YE', 'name' => 'Yemen', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'YER', 'continent' => 'Asia'],
            ['code' => 'OM', 'name' => 'Oman', 'vat_rate' => 5.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'OMR', 'continent' => 'Asia'],
            ['code' => 'QA', 'name' => 'Qatar', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'QAR', 'continent' => 'Asia'],
            ['code' => 'BH', 'name' => 'Bahrain', 'vat_rate' => 5.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BHD', 'continent' => 'Asia'],
            ['code' => 'KW', 'name' => 'Kuwait', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'KWD', 'continent' => 'Asia'],

            // Africa
            ['code' => 'ZA', 'name' => 'South Africa', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ZAR', 'continent' => 'Africa'],
            ['code' => 'NG', 'name' => 'Nigeria', 'vat_rate' => 7.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'NGN', 'continent' => 'Africa'],
            ['code' => 'EG', 'name' => 'Egypt', 'vat_rate' => 14.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'EGP', 'continent' => 'Africa'],
            ['code' => 'KE', 'name' => 'Kenya', 'vat_rate' => 16.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'KES', 'continent' => 'Africa'],
            ['code' => 'GH', 'name' => 'Ghana', 'vat_rate' => 12.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'GHS', 'continent' => 'Africa'],
            ['code' => 'UG', 'name' => 'Uganda', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'UGX', 'continent' => 'Africa'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'TZS', 'continent' => 'Africa'],
            ['code' => 'ET', 'name' => 'Ethiopia', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ETB', 'continent' => 'Africa'],
            ['code' => 'MA', 'name' => 'Morocco', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MAD', 'continent' => 'Africa'],
            ['code' => 'DZ', 'name' => 'Algeria', 'vat_rate' => 19.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'DZD', 'continent' => 'Africa'],
            ['code' => 'TN', 'name' => 'Tunisia', 'vat_rate' => 19.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'TND', 'continent' => 'Africa'],
            ['code' => 'LY', 'name' => 'Libya', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'LYD', 'continent' => 'Africa'],
            ['code' => 'SD', 'name' => 'Sudan', 'vat_rate' => 17.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SDG', 'continent' => 'Africa'],
            ['code' => 'SS', 'name' => 'South Sudan', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SSP', 'continent' => 'Africa'],
            ['code' => 'CD', 'name' => 'Democratic Republic of Congo', 'vat_rate' => 16.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CDF', 'continent' => 'Africa'],
            ['code' => 'CG', 'name' => 'Republic of Congo', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XAF', 'continent' => 'Africa'],
            ['code' => 'AO', 'name' => 'Angola', 'vat_rate' => 14.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AOA', 'continent' => 'Africa'],
            ['code' => 'ZM', 'name' => 'Zambia', 'vat_rate' => 16.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ZMW', 'continent' => 'Africa'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'vat_rate' => 14.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ZWL', 'continent' => 'Africa'],
            ['code' => 'BW', 'name' => 'Botswana', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BWP', 'continent' => 'Africa'],
            ['code' => 'NA', 'name' => 'Namibia', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'NAD', 'continent' => 'Africa'],
            ['code' => 'MW', 'name' => 'Malawi', 'vat_rate' => 16.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MWK', 'continent' => 'Africa'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'vat_rate' => 17.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MZN', 'continent' => 'Africa'],
            ['code' => 'MG', 'name' => 'Madagascar', 'vat_rate' => 20.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MGA', 'continent' => 'Africa'],
            ['code' => 'MU', 'name' => 'Mauritius', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MUR', 'continent' => 'Africa'],
            ['code' => 'SC', 'name' => 'Seychelles', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SCR', 'continent' => 'Africa'],
            ['code' => 'RW', 'name' => 'Rwanda', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'RWF', 'continent' => 'Africa'],
            ['code' => 'BI', 'name' => 'Burundi', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BIF', 'continent' => 'Africa'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'DJF', 'continent' => 'Africa'],
            ['code' => 'SO', 'name' => 'Somalia', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SOS', 'continent' => 'Africa'],
            ['code' => 'ER', 'name' => 'Eritrea', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'ERN', 'continent' => 'Africa'],
            ['code' => 'SN', 'name' => 'Senegal', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XOF', 'continent' => 'Africa'],
            ['code' => 'GM', 'name' => 'Gambia', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'GMD', 'continent' => 'Africa'],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'vat_rate' => 17.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XOF', 'continent' => 'Africa'],
            ['code' => 'GN', 'name' => 'Guinea', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'GNF', 'continent' => 'Africa'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SLL', 'continent' => 'Africa'],
            ['code' => 'LR', 'name' => 'Liberia', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'LRD', 'continent' => 'Africa'],
            ['code' => 'CI', 'name' => 'Ivory Coast', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XOF', 'continent' => 'Africa'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XOF', 'continent' => 'Africa'],
            ['code' => 'ML', 'name' => 'Mali', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XOF', 'continent' => 'Africa'],
            ['code' => 'NE', 'name' => 'Niger', 'vat_rate' => 19.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XOF', 'continent' => 'Africa'],
            ['code' => 'TD', 'name' => 'Chad', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XAF', 'continent' => 'Africa'],
            ['code' => 'CF', 'name' => 'Central African Republic', 'vat_rate' => 19.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XAF', 'continent' => 'Africa'],
            ['code' => 'CM', 'name' => 'Cameroon', 'vat_rate' => 19.25, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XAF', 'continent' => 'Africa'],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XAF', 'continent' => 'Africa'],
            ['code' => 'GA', 'name' => 'Gabon', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XAF', 'continent' => 'Africa'],
            ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'STN', 'continent' => 'Africa'],
            ['code' => 'CV', 'name' => 'Cape Verde', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CVE', 'continent' => 'Africa'],
            ['code' => 'MR', 'name' => 'Mauritania', 'vat_rate' => 14.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MRU', 'continent' => 'Africa'],
            ['code' => 'EH', 'name' => 'Western Sahara', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'MAD', 'continent' => 'Africa'],

            // Oceania
            ['code' => 'AU', 'name' => 'Australia', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AUD', 'continent' => 'Oceania'],
            ['code' => 'NZ', 'name' => 'New Zealand', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'NZD', 'continent' => 'Oceania'],
            ['code' => 'FJ', 'name' => 'Fiji', 'vat_rate' => 9.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'FJD', 'continent' => 'Oceania'],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'PGK', 'continent' => 'Oceania'],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'SBD', 'continent' => 'Oceania'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'vat_rate' => 12.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'VUV', 'continent' => 'Oceania'],
            ['code' => 'NC', 'name' => 'New Caledonia', 'vat_rate' => 6.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XPF', 'continent' => 'Oceania'],
            ['code' => 'PF', 'name' => 'French Polynesia', 'vat_rate' => 5.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'XPF', 'continent' => 'Oceania'],
            ['code' => 'CK', 'name' => 'Cook Islands', 'vat_rate' => 12.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'NZD', 'continent' => 'Oceania'],
            ['code' => 'NU', 'name' => 'Niue', 'vat_rate' => 12.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'NZD', 'continent' => 'Oceania'],
            ['code' => 'TO', 'name' => 'Tonga', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'TOP', 'continent' => 'Oceania'],
            ['code' => 'WS', 'name' => 'Samoa', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'WST', 'continent' => 'Oceania'],
            ['code' => 'KI', 'name' => 'Kiribati', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AUD', 'continent' => 'Oceania'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AUD', 'continent' => 'Oceania'],
            ['code' => 'NR', 'name' => 'Nauru', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'AUD', 'continent' => 'Oceania'],
            ['code' => 'PW', 'name' => 'Palau', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'USD', 'continent' => 'Oceania'],
            ['code' => 'FM', 'name' => 'Micronesia', 'vat_rate' => 4.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'USD', 'continent' => 'Oceania'],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'USD', 'continent' => 'Oceania'],

            // Caribbean
            ['code' => 'CU', 'name' => 'Cuba', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'CUP', 'continent' => 'North America'],
            ['code' => 'JM', 'name' => 'Jamaica', 'vat_rate' => 15.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'JMD', 'continent' => 'North America'],
            ['code' => 'HT', 'name' => 'Haiti', 'vat_rate' => 10.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'HTG', 'continent' => 'North America'],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'vat_rate' => 18.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'DOP', 'continent' => 'North America'],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'vat_rate' => 10.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'USD', 'continent' => 'North America'],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'vat_rate' => 12.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'TTD', 'continent' => 'North America'],
            ['code' => 'BB', 'name' => 'Barbados', 'vat_rate' => 17.50, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BBD', 'continent' => 'North America'],
            ['code' => 'BS', 'name' => 'Bahamas', 'vat_rate' => 12.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BSD', 'continent' => 'North America'],
            ['code' => 'BM', 'name' => 'Bermuda', 'vat_rate' => 0.00, 'is_eu_member' => false, 'vies_validation_required' => false, 'currency_code' => 'BMD', 'continent' => 'North America'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
